import { pathFunctionRequest } from "../variableGlobal/varPath";

const objectRouterFunctionRequest = {
  dashboard:{
    title: "Dashboard Function Request ",
    path: pathFunctionRequest,
		stringElement: "DashboardPage",
    index: true,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
  },
  fnRequest:{
    title: "New Function Request",
    path: `${pathFunctionRequest}/new_function_request`,
    stringElement: "NewFunctionRequest",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  submitNonBulkFunctionRequest:{
    title: "New Function Request",
    path: `${pathFunctionRequest}/new_function_request/submit_non_bulk_function_request`,
    stringElement: "CreateFunctionRequest",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "C",
  },
  editNonBulkFunctionRequest:{
    title: "Edit Function Request",
    path: `${pathFunctionRequest}/new_function_request/edit_non_bulk_function_request`,
    stringElement: "EditOrViewFunctionRequest",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  submitBulkFunctionRequest:{
    title: "New Function Request",
    path: `${pathFunctionRequest}/new_function_request/submit_bulk_function_request`,
    stringElement: "CreateBulkFunctionRequest",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "C",
  },
  requestTransactionList:{
    title: "request transaction list",
    path: `${pathFunctionRequest}/request_transaction_list`,
    stringElement: "IndexRequestTransactionList",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  editRequestTransactionList:{
    title: "request transaction list",
    path: `${pathFunctionRequest}/request_transaction_list/edit`,
    stringElement: "EditAndViewRequestTransaction",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  viewRequestTransactionList:{
    title: "request transaction list",
    path: `${pathFunctionRequest}/request_transaction_list/view`,
    stringElement: "EditAndViewRequestTransaction",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
}

export default objectRouterFunctionRequest