import { pathMasterPage } from "../variableGlobal/varPath";

const objectRouterMasterPage = {
  dashboard:{
    title: "master page",
    path: pathMasterPage,
    stringElement: "DashboardPage",
    index: true,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
  },
  product:{
    title: "master product",
    path: `${pathMasterPage}/product`,
    stringElement: "ProductPage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  createProduct:{
    title: "create product",
    path: `${pathMasterPage}/product/add-new-product`,
    stringElement: "CreateProduct",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "C",
  },
  editProduct:{
    title: "edit product",
    path: `${pathMasterPage}/product/edit-product`,
    stringElement: "EditProduct",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  viewProduct:{
    title: "edit product",
    path: `${pathMasterPage}/product/view-product`,
    stringElement: "EditProduct",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  tenant:{
    title: "master tenant",
    path: `${pathMasterPage}/tenant`,
    stringElement: "TenantIndexPage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  createTenant:{
    title: "create tenant",
    path: `${pathMasterPage}/tenant/add-new-tenant`,
    stringElement: "CreateTenant",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "C",
  },
  editTenant:{
    title: "edit tenant",
    path: `${pathMasterPage}/tenant/edit-tenant`,
    stringElement: "EditTenant",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  viewTenant:{
    title: "view tenant",
    path: `${pathMasterPage}/tenant/view-tenant`,
    stringElement: "EditTenant",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  productPackage:{
    title: "master package",
    path: `${pathMasterPage}/package-product`,
    stringElement: "ProductPackage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  createProductPackage:{
    title: "create product package",
    path: `${pathMasterPage}/package-product/add-new-package`,
    stringElement: "CreateProductPackage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "C",
  },
  editProductPackage:{
    title: "edit product package",
    path: `${pathMasterPage}/package-product/edit-package`,
    stringElement: "EditProductPackage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  viewProductPackage:{
    title: "view product package",
    path: `${pathMasterPage}/package-product/view-package`,
    stringElement: "EditProductPackage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  productPromo:{
    title: "master promo",
    path: `${pathMasterPage}/promo-product`,
    stringElement: "ProductPromo",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  createProductPromo:{
    title: "create product promo",
    path: `${pathMasterPage}/promo-product/add-new-promo`,
    stringElement: "CreateProductPromo",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "C",
  },
  editProductPromo:{
    title: "edit product promo",
    path: `${pathMasterPage}/promo-product/edit-promo`,
    stringElement: "EditProductPromo",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  viewProductPromo:{
    title: "view product promo",
    path: `${pathMasterPage}/promo-product/view-promo`,
    stringElement: "EditProductPromo",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  room:{
    title: "master room",
    path: `${pathMasterPage}/room`,
    stringElement: "RoomIndexPage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  createRoom:{
    title: "create room",
    path: `${pathMasterPage}/room/add-new-room`,

    stringElement: "CreateRoom",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "C",
  },
  editRoom:{
    title: "edit room",
    path: `${pathMasterPage}/room/edit-room`,
    stringElement: "EditRoom",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  viewRoom:{
    title: "view room",
    path: `${pathMasterPage}/room/view-room`,
    stringElement: "EditRoom",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  lookupValue:{
    title: "master lookup value",
    path: `${pathMasterPage}/lookup-value`,
    stringElement: "LookupValuePage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  createlookupValue:{
    title: "create lookup value",
    path: `${pathMasterPage}/lookup-value/add-new-lookup-value`,
    stringElement: "CreateLookupValue",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "C",
  },
  editlookupValue:{
    title: "edit lookup value",
    path: `${pathMasterPage}/lookup-value/edit-lookup-value`,
    stringElement: "EditLookupValue",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  viewLookupValue:{
    title: "view lookup value",
    path: `${pathMasterPage}/lookup-value/view-lookup-value`,
    stringElement: "EditLookupValue",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  oneTimeSetup:{
    title: "Configuration",
    path: `${pathMasterPage}/one-time-setup`,
    stringElement: "OneTimeSetupPage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
}

export default objectRouterMasterPage;