import { pathInquiry } from "../variableGlobal/varPath";

const objectRouterInquiry = {
  dashboard:{
    title: "Dashboard Inquiry",
    path: pathInquiry,
		stringElement: "DashboardPage",
    index: true,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
  },
  orderHistoryList:{
    title: "Order History List and View",
    path: `${pathInquiry}/order-history-list`,
    stringElement: "OrderHistoryListPage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  viewOrderHistoryList:{
    title: "view Order History List and View",
    path: `${pathInquiry}/order-history-list/view-order`,
    stringElement: "EditOrderHistoryListPage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  editOrderHistoryList:{
    title: "Edit Order History List and View",
    path: `${pathInquiry}/order-history-list/edit-order`,
    stringElement: "EditOrderHistoryListPage",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "U",
  },
  requestCommentAndReview:{
    title: "request comment and review",
    path: `${pathInquiry}/request-comment-and-review`,
    stringElement: "RequestCommentAndReview",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  formRequestCommentAndReview:{
    title: "request comment and review",
    path: `${pathInquiry}/request-comment-and-review/form-review`,
    stringElement: "RateRequestCommentAndReview",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  tenantRequestCommentAndReview:{
    title: "tenant request comment and review",
    path: `${pathInquiry}/tenant-request-comment-and-review`,
    stringElement: "TenantRequestCommentAndReview",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
  tenantFormRequestCommentAndReview:{
    title: "tenant request comment and review",
    path: `${pathInquiry}/tenant-request-comment-and-review/form-review`,
    stringElement: "TenantRateRequestCommentAndReview",
    index: false,
    needAuth: true,
    header: true,
    footer: false,
    sidebar: true,
    privileges: "R",
  },
}

export default objectRouterInquiry